OPENAI_API_KEY = "OPENAI_API_KEY = "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"
